language: ruby
before_install: gem update --system 1.8.25
rvm:
 - 1.9.3
 - 2.0.0
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: 2.0.0
notifications:
  email:
    - john.bellone.jr@gmail.com
